apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: social-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.14
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
