apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: social-feed
spec:
  selector:
    app: postgres
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
